name: Maven CI/CD

on:
  push:
    branches: [ yannick ]
  pull_request:
    branches: [ yannick ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
    
    - name: create a directory and copy dependency file
      run: mkdir staging && cp target/*jar-with-dependencies.jar staging

    - name: upload artifact 
      uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging